(async () => {
  const projectId = new URLSearchParams(location.search).get("id");
  const editor = document.querySelector("#editor"), revisionForm = document.querySelector("#revisionForm"), pointList = document.querySelector("#pointList"), notice = document.querySelector("#editorNotice");
  let project, revision;
  const csrf = () => decodeURIComponent((document.cookie.split(";").map((part) => part.trim()).find((part) => part.startsWith("hifly_identity_csrf=")) || "=").split("=").slice(1).join("="));
  async function request(url, options = {}) { const headers = new Headers(options.headers || {}); if (options.method && options.method !== "GET") headers.set("x-identity-csrf", csrf()); const response = await fetch(url, { credentials: "same-origin", ...options, headers }); if ([401,403].includes(response.status)) { location.replace("/login.html"); throw new Error("AUTH_REQUIRED"); } const body = await response.json(); if (!response.ok) throw Object.assign(new Error(body.error), { body, status: response.status }); return body; }
  function pointRow(point = { text: "", confirmed: false }) { const row = document.createElement("div"); row.className = "point-row"; row.dataset.id = point.id || ""; row.dataset.confirmed = String(point.confirmed); const label = document.createElement("label"); label.textContent = point.confirmed ? "已确认卖点" : "待确认卖点"; const input = document.createElement("input"); input.value = point.text; input.addEventListener("input", () => { if (row.dataset.confirmed === "true" && input.value.trim() !== point.text) { row.dataset.confirmed = "false"; label.firstChild.textContent = "待确认卖点"; } }); const confirm = document.createElement("button"); confirm.type = "button"; confirm.className = "secondary"; confirm.textContent = point.confirmed ? "已确认" : "确认"; confirm.disabled = point.confirmed; confirm.addEventListener("click", async () => { if (!row.dataset.id) { notice.className = "notice blocked"; notice.textContent = "请先保存草稿，再确认卖点。"; return; } await confirmPoint(row.dataset.id); }); label.append(input); row.append(label, confirm); return row; }
  function renderRevision(value) { revision = value; editor.hidden = false; const state = document.querySelector("#revisionState"); state.className = `state ${revision.status}`; state.textContent = `${revision.status} · v${revision.revision_number}`; revisionForm.product_name.value = revision.product_name; revisionForm.product_description.value = revision.product_description || ""; revisionForm.primary_category.value = revision.primary_category; revisionForm.expression_style.value = revision.content_brief?.expression_style || ""; revisionForm.additional_requirements.value = revision.content_brief?.additional_requirements || ""; pointList.replaceChildren(...revision.selling_points.map(pointRow)); const readyButton = document.querySelector("#readyRevision"); readyButton.disabled = revision.status === "ready"; readyButton.title = revision.status === "ready" ? "当前快照已 Ready；修改并保存草稿后可再次 Ready" : ""; notice.textContent = ""; }
  function renderProducts() { const list = document.querySelector("#productList"); list.replaceChildren(); if (!project.products.length) { list.innerHTML = '<p class="empty">还没有商品</p>'; return; } for (const item of project.products) { const button = document.createElement("button"); button.type = "button"; button.className = "secondary"; button.textContent = `${item.revision.product_name || "未命名商品"} · ${item.revision.status}`; button.addEventListener("click", () => renderRevision(item.revision)); list.append(button); } }
  async function loadProject(selectRevisionId = revision?.id) { project = (await request(`/api/projects/${projectId}`)).project; document.querySelector("#projectName").textContent = project.name; renderProducts(); const selected = project.products.find((item) => item.revision.id === selectRevisionId) || project.products[0]; if (selected) renderRevision(selected.revision); }
  async function loadAssets() { const box = document.querySelector("#assetOptions"); const assets = (await request("/api/assets")).assets.flatMap((asset) => asset.versions.filter((version) => version.status === "available")); box.replaceChildren(); if (!assets.length) { box.innerHTML = '<p class="empty">没有可引用的商品图片</p>'; return; } for (const asset of assets) { const label = document.createElement("label"); label.className = "asset-option"; const input = document.createElement("input"); input.type = "checkbox"; input.value = asset.id; input.checked = revision?.asset_version_ids.includes(asset.id) || false; label.append(input, document.createTextNode(`${asset.original_filename} · 版本 ${asset.version_number}`)); box.append(label); } }
  function payload() { return { expected_revision: revision.revision_number, product_name: revisionForm.product_name.value, product_description: revisionForm.product_description.value, primary_category: revisionForm.primary_category.value, content_brief: { expression_style: revisionForm.expression_style.value, additional_requirements: revisionForm.additional_requirements.value }, selling_points: [...pointList.children].map((row) => ({ ...(row.dataset.id ? { id: row.dataset.id } : {}), text: row.querySelector("input").value })), asset_version_ids: [...document.querySelectorAll("#assetOptions input:checked")].map((input) => input.value) }; }
  async function save() { notice.className = "notice"; notice.textContent = "正在保存..."; try { renderRevision((await request(`/api/product-revisions/${revision.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload()) })).revision); await loadAssets(); notice.className = "notice success"; notice.textContent = revision.status === "ready" ? "当前 Ready 快照未变化。" : "草稿已保存。"; return true; } catch (error) { if (error.status === 409) { notice.className = "notice blocked"; notice.textContent = "页面内容已过期，请刷新后继续。"; } else notice.className = "notice error"; notice.textContent = "保存失败，请稍后重试。"; return false; } }
  async function confirmPoint(id) { if (!(await save())) return; const current = revision.selling_points.find((point) => point.id === id); renderRevision((await request(`/api/product-revisions/${revision.id}/selling-points/${id}/confirm`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ expected_revision: revision.revision_number }) })).revision); await loadAssets(); notice.className = "notice success"; notice.textContent = `“${current.text}”已确认。`; }
  document.querySelector("#productForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = event.currentTarget; try { const result = await request(`/api/projects/${projectId}/products`, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ product_name: form.product_name.value }) }); form.reset(); await loadProject(result.revision.id); await loadAssets(); } catch (_error) { document.querySelector("#productError").textContent = "商品创建失败，请重试。"; } });
  revisionForm.addEventListener("submit", async (event) => { event.preventDefault(); await save(); }); document.querySelector("#addPoint").addEventListener("click", () => pointList.append(pointRow())); document.querySelector("#refreshRevision").addEventListener("click", async () => { await loadProject(); await loadAssets(); });
  document.querySelector("#readyRevision").addEventListener("click", async () => { if (!(await save())) return; try { const ready = (await request(`/api/product-revisions/${revision.id}/ready`, { method: "POST", headers: { "content-type": "application/json", "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ expected_revision: revision.revision_number }) })).revision; await loadProject(ready.id); notice.className = "notice success"; notice.textContent = "商品快照已 Ready。"; } catch (error) { if (error.message === "PRODUCT_REVISION_READY_BLOCKED") { const labels = { PRODUCT_NAME_REQUIRED: "填写商品名称", SELLING_POINT_REQUIRED: "确认至少一条卖点", IMAGE_REQUIRED: "选择至少一张可引用图片" }; notice.className = "notice blocked"; notice.textContent = `暂不能 Ready：${error.body.reasons.map((item) => labels[item.code]).join("、")}。`; } else { notice.className = "notice error"; notice.textContent = "Ready 操作失败，请稍后重试。"; } } });
  if (!projectId) return location.replace("/projects.html"); const runtime = await request("/api/runtime"); if (!runtime.projectContentEnabled) return location.replace("/"); await loadProject(); if (runtime.assetsEnabled) await loadAssets();
})();
